### ISSUE TITLE
roq-samples README is outdated

### ISSUE THREAD

**Issue by IlyaKrotov** [roq-trading/roq-feedback#2]
https://github.com/roq-trading/roq-samples/blob/master/README.md

I tried to follow this readme and install your samples, but it turned out to be a waste of time. Could you explain how to build it? I can help renew this manual then. Also, your website is not working properly.

**Comment by thraneh** [comment]
I have just followed all the steps from the README and project compiled fine.

Perhaps there is some variation based on your Linux distribution and/or environment. Could you please provide me with details about your setup and exactly what issues you're observing?

I also can't find any particular issues with the website. Again, could you provide the details of what you're observing?

**Comment by IlyaKrotov** [comment]
Thank you for the fast response! Let's start from building issues.

I'm trying to run this using macOS, then I can try my ubuntu remote. Instead of miniconda I'm using conda, but I guess this is not the problem. 

```
(base)  ~/Desktop/Personal/Traders/roq-samples: conda install -y roq-client
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.

PackagesNotFoundError: The following packages are not available from current channels:

  - roq-client

Current channels:

  - https://roq-trading.com/conda/unstable/osx-64
  - https://roq-trading.com/conda/unstable/noarch
  - https://repo.anaconda.com/pkgs/main/osx-64
  - https://repo.anaconda.com/pkgs/main/noarch
  - https://repo.anaconda.com/pkgs/r/osx-64
  - https://repo.anaconda.com/pkgs/r/noarch
  - https://conda.anaconda.org/conda-forge/osx-64
  - https://conda.anaconda.org/conda-forge/noarch

To search for alternate channels that may provide the conda package you're
looking for, navigate to

    https://anaconda.org

and use the search bar at the top of the page.
```

So, conda cannot find this package. I tried stable, but I didn't succeed. Do you think this is because of the host system?

**Comment by IlyaKrotov** [comment]
I'm going to try this on Ubuntu 16.04.3 LTS. Are there any special steps?

**Comment by IlyaKrotov** [comment]
Take my words back, I haven't found any problems with Ubuntu 16.04.3 LTS. Guess it is only with macOS due to conda packages.

**Comment by IlyaKrotov** [comment]
Could you explain this? I followed your guide and tried to run example 3. I wanted to simulate your strategy on your data, even Deribit gateway is configured and running in a different session. 

```
~/roq-samples/src/roq/samples/example-3# ./roq-samples-example-3 --name "example-3"  --simulation  $CONDA_PREFIX/share/roq/data/deribit.roq  --enable-trading
I0320 08:02:25.960400 50525 application.cpp:43] ===== START =====
I0320 08:02:25.966731 50525 main.cpp:183] [deribit:BTC-27MAR20] connection_status=CONNECTED
I0320 08:02:25.969504 50525 main.cpp:233] [deribit:BTC-27MAR20] market_data_status=CONNECTING
I0320 08:02:25.969524 50525 main.cpp:247] [deribit:BTC-27MAR20] order_manager_status=CONNECTING
I0320 08:02:25.969535 50525 main.cpp:233] [deribit:BTC-27MAR20] market_data_status=LOGIN_SENT
I0320 08:02:25.969545 50525 main.cpp:247] [deribit:BTC-27MAR20] order_manager_status=LOGIN_SENT
I0320 08:02:25.969633 50525 main.cpp:264] [deribit:BTC-27MAR20] tick_size=0.5
I0320 08:02:25.969647 50525 main.cpp:271] [deribit:BTC-27MAR20] min_trade_vol=1.0
I0320 08:02:25.969656 50525 main.cpp:278] [deribit:BTC-27MAR20] multiplier=10.0
I0320 08:02:25.969686 50525 main.cpp:293] [deribit:BTC-27MAR20] trading_status=OPEN
I0320 08:02:25.969823 50525 main.cpp:233] [deribit:BTC-27MAR20] market_data_status=DOWNLOADING
I0320 08:02:25.969838 50525 main.cpp:247] [deribit:BTC-27MAR20] order_manager_status=DOWNLOADING
I0320 08:02:26.746510 50525 main.cpp:183] [deribit:BTC-27MAR20] connection_status=DISCONNECTED
I0320 08:02:26.750597 50525 application.cpp:46] ===== STOP =====
```

**Comment by thraneh** [comment]
The solution is currently only available for Linux.
Great to hear that you've managed to get it all working with Ubuntu.

A few comments about the example you mentioned:
You can enable verbose logging by exporting (or prefixing your command line with) ROQ_v=1 (or some higher number).
The logs you're showing are based on replaying collected data (indicated by the --simulation command line argument).
You can run the example against a live gateway if you replace `--simulation <path>` with a path to the Unix domain socket exported by the gateway.

A while ago I wrote a blog describing some features of the entire system design: [ShowHN](https://roq-trading.com/docs/blogs/showhn/)
The last part of the blog describes how to connect to a live gateway.

**Comment by IlyaKrotov** [comment]
Hello again! I've found your solution exceptionally good and usable! But I always receive the same error after my strategy submits order:

```
I0326 08:30:01.868565 45612 fix.cpp:122] request(new_order_single={cl_ord_id="roq-19", side=BUY, order_qty=10.0, price=6593.0, symbol="BTC-PERPETUAL", exec_inst="", ord_type=LIMIT, time_in_force=GTC, deribit_label="roq-10000001-1-1001", deribit_adv_order_type=''})
I0326 08:30:01.869526 45612 pollster.cpp:236] OrderAck={account="A1", order_id=1001, type=CREATE_ORDER, origin=GATEWAY, status=FORWARDED, error=UNDEFINED, text="", gateway_order_id=10000001, external_order_id="", request_id="roq-19"}
C0326 08:30:07.178695 45612 fix.cpp:358] ERROR what="commissions should not decrease"
*** TERMINATION HANDLER ***
Aborted (Signal sent by tkill() 45611 0)
[ 0]     0x7fe1028ac3ad roq::Application::run()
[ 1]     0x7fe1019b3390 funlockfile
[ 2]     0x7fe10160d428 gsignal
[ 3]     0x7fe10160f02a abort
[ 4]     0x7fe1028ac4a2 roq::Application::run()
[ 5]     0x56415f0f473b roq::detail::LogMessage::~LogMessage()
[ 6]     0x56415f110394 roq::deribit::FIX::operator()(roq::core::net::Manager::Read const&)
[ 7]     0x56415f16fafe roq::core::net::Manager::operator()(roq::core::net::Connection::Read const&)
[ 8]     0x56415f1734d5 roq::core::net::TcpConnection::on_read()
[ 9]     0x56415f17475f roq::core::event::BufferEvent::read_callback(bufferevent*, void*)
[10]     0x7fe102843522 bufferevent_readcb
[11]     0x7fe10284870e event_process_active_single_queue.isra.29
[12]     0x7fe102848dc7 event_base_loop
[13]     0x56415f16908f roq::core::event::Base::loop(int)
[14]     0x7fe102941f02 _init
[15]     0x7fe102991747 std::_Rb_tree<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::set<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > >, std::_Select1st<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::set<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > > >, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::set<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > > > >::_M_erase(std::_Rb_tree_node<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::set<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > > >*)
[16]     0x7fe101f9019d execute_native_thread_routine
[17]     0x7fe1019a96ba start_thread
[18]     0x7fe1016df41d clone
Aborted (core dumped)
```

Also, I haven't found how to add instruction to make orders post-only. Is it possible?

**Comment by thraneh** [comment]
First question;

This is one of many assertions. In this case I didn't know if the commissions were cumulative or per-trade. (It appears to be the latter).

For now I have removed the assertion and dropped the propagation of commissions until I get around to implementing a safe way to accumulate those.

The `roq-deribit` package has been rebuilt for unstable. Safest is to recreate your conda environment.  Alternatively, you can try `conda update --force-reinstall roq-deribit` and be careful to note that dependencies are updated as well.


Second question;

The Roq API doesn't currently support `post only` and `reduce only`. Deribit supports it (`ExecInst` using FIX). I will add API support for this in the near future and post an update here when it's ready.


Finally, do you mind open a new issue each time you encounter something? It might help other users to more easily find explanations and solutions if they encounter similar problems.


Many thanks for the nice feedback. With your help I think we can quickly get this solution production ready.

**Comment by IlyaKrotov** [comment]
Sure, I will open new issues for different problems, thanks for the response

**Comment by thraneh** [comment]
The API has now been extended to support post only orders.

The `CreateOrder` template now allows you to specify further fields, namely `execution_instruction`, `stop_price` and `max_show_quantity`.

For post only orders, you'll have to specify `ExecutionInstruction::PARTICIPATE_DO_NOT_INITIATE` and leave the other two new fields as NaN.

Some further information:

Each gateway is responsible for checking the validity of `CreateOrder` fields before sending a request to the exchange.

Deribit's FIX interface does not appear to support stop limit orders: the gateway will therefore emit an error if you specify a stop price (i.e. something else than NaN).
